skillnecting/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    """Class for Posting content to blog"""
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')


skillnecting/api/routes.py
from flask import request, Blueprint, jsonify, render_template
from skillnecting.models import User, Post

api = Blueprint('api', __name__)


@api.route("/api")
def api_route():
	return render_template("api.html")

@api.route("/api/users", methods=['GET', 'POST'])
def api_users():
    users = User.query.all()
    user_dict = {}
    print(users)
    if request.method == 'GET':
        for users in  users:
            user_dict[users.username] = users.github_username
        total_users = {'Total Users': len(user_dict)}
        return jsonify(user_dict, total_users), 201


@api.route("/api/users/techskills", methods=['GET', 'POST'])
def api_techskills():
	users = User.query.all()
	user_techskills = {}
	tech_list = []
	if request.method == 'GET':
		for users in  users:
			user_techskills[users.username] = str(users.techskills)
		total_users = {'Total Users': len(user_techskills)}
		return jsonify	(user_techskills, total_users), 201


@api.route("/api/users/posts", methods=['GET', 'POST'])
def api_posts():
	posts = Post.query.all()
	post_dict = {}
	author_post = []
	if request.method == 'GET':
		for items in posts:
			author_post.append(items.title)
			post_dict[items.author.github_username] = author_post
			#print(items.author.github_username)
		return jsonify(post_dict), 201

skillnecting/main/routes.py
from flask import render_template, request, Blueprint, jsonify
from skillnecting.models import Post, User
from flask import render_template, request, Blueprint, jsonify
from skillnecting.models import Post, User
from sqlalchemy import func

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
	#users = User.query.all()
	users = User.query.order_by(func.random()).limit(3).all()
	print(dir(users))
	return render_template("landing-page.html", users=users)

@main.route("/blog")
def blog():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template("blog.html", posts=posts)


@main.route("/about")
def about():
    return render_template("about.html", title='About')

"""
@main.route("/api/users", methods=['GET', 'POST'])
def api_users():
        users = User.query.all()
        user_list = []
        print(users)
        if request.method == 'GET':
                for users in  users:
                        user_list.append(users.username)
                return jsonify({"usernames": user_list}), 201
"""

skillnecting/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from skillnecting import db
from skillnecting.models import Post
from skillnecting.posts.forms import PostForm

posts = Blueprint('posts', __name__)

@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    """Function for posting adding new post to blog"""
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title="New Post", form=form, legend='Update Post')


@posts.route("/post/<int:post_id>")
def post(post_id):
    """Function to find post by id"""
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    """Function to update posts"""
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', form=form, legend='Update Post')

@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    """Function to delete post"""
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been Deleted!', 'success')
    return redirect(url_for('main.home'))

skillnecting/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, g
from flask_login import login_user, current_user, logout_user, login_required
from skillnecting import db, bcrypt, github
from skillnecting.models import User, Post, Technicalskills, GithubUser
from skillnecting.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from skillnecting.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    """function to register new user
        Take data from registration form
        hash password using bcrypt and then store user details into db
    """
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(
            username=form.username.data,
            email=form.email.data,
            password=hashed_password,
            github_username=form.github_username.data,
            user_designation = form.user_designation.data)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('sign-up.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    """Funtion to validate username and password"""
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(
                user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            """login_user takes two paramenters
                user: takes data from user and queries data base to find if it exits
                if exists, uses bcrypt.check_password_hash to 
                validate is password is correct
                remember: enables form to remember data is user checks true
            """
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(
                url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login-page.html', title='Login', form=form)


@users.route('/github_login')
def github_login():
    """Function and route to redirect user to git hub to authorize"""
    return github.authorize()


@users.route('/github-callback')
@github.authorized_handler
def authorized(oauth_token):
    next_url = request.args.get('next') or url_for('main.home')
    if oauth_token is None:
        flash("Authorization failed.")
        return redirect(next_url)

    user = GithubUser.query.filter_by(github_access_token=oauth_token).first()
    if user is None:
        user = GithubUser(github_access_token=oauth_token)
        db.session.add(user)

    user.github_access_token = oauth_token
    db.session.commit()
    login_user(user, True)
    return redirect(next_url)


@github.access_token_getter
def token_getter():
    user = g.user
    if user is not None:
        return user.github_access_token



@users.route("/logout")
def logout():
    """Function to logout users"""
    print(request.referrer)
    logout_user()
    return redirect(request.referrer)


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    """Function to return/update user account"""
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        if form.techskills.data:
            for items in form.techskills.data:
                tech_skill = Technicalskills(name=items)
                tech_skill.user.append(current_user)
        current_user.user_weblink = form.user_weblink.data
        current_user.user_designation = form.user_designation.data
        current_user.short_description = form.short_description.data
        db.session.commit()
        print(form.data)
        flash('Your account has been updated', 'success')
        return redirect(url_for('users.user_profile', username=current_user.username))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.techskills.data = current_user.techskills
        form.user_weblink.data = current_user.user_weblink
        form.user_designation.data = current_user.user_designation
        form.short_description.data = current_user.short_description
    image_file = url_for('static', filename="profile_pics/" + current_user.image_file)
    return render_template('account.html', title="Account", image_file=image_file, form=form)


@users.route("/<string:username>/posts")
def user_posts(username):
    """Function to return posts per user"""
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template("user_post.html", posts=posts, user=user)


@users.route("/<string:username>/delete", methods=['POST'])
@login_required
def delete_user(username):
    """Function to delete post"""
    user = User.query.filter_by(username=username).first_or_404()
    db.session.delete(user)
    db.session.commit()
    flash('Your Profile has been Deleted!', 'success')
    return redirect(url_for('main.home'))


@users.route("/home/<string:username>")
@users.route("/<string:username>")
def user_profile(username):
    """Funtion to return User profile"""
    user = User.query.filter_by(username=username).first_or_404()
    print(user)
    return render_template("profile-page.html", user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    """Function to get request to reset password"""
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password', 'info')
        return redirect(url_for('main.login'))
    return render_template("reset_request.html", title="Reset Password", form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    """Function to reset token"""
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your Password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template("reset_token.html", title="Reset Password", form=form)



skillnecting/templates/api.html
{% extends "layout.html" %}

{% block content %}
{% endblock content %}

skillnecting/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- FAVICON -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <link href="https://image.ibb.co/fZNTHz/skillnecting.png?{{ cache_id }}" rel="icon" type="image/png">

    {% if title %}
        <title>Skillnecting - {{ title }}</title>
    {% else %}
        <title>Skillnecting</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          {% if current_user.is_authenticated %}
        <a class="navbar-brand" href="/">{{current_user.username}}@Skillnecting</a>
        {% else %}
        <a class="navbar-brand" href="/">Skillnecting</a>
        {% endif %}
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
	      
	    </div>
          </div>
            <!-- Navbar 
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
            Right Side -->
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-12">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

skillnecting/templates/post.html
{% extends "layout.html" %}
{% block content %}
<article class="media content-section">
	<img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
  	<div class="media-body">
   		<div class="article-metadata">
      		<a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
      		<small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
    	</div>
      <div class="content-section">
        <h2 class="article-title">{{ post.title }}</h2>
        <p class="article-content">{{ post.content }}</p>
      </div>
    	{% if post.author == current_user %}
            <div>
              <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
              <button type="button" class="btn btn-danger btn-sm m-1" data-toggle='modal' data-target='#deleteModal'>Delete</button>
            </div>
          {% endif %}
  	</div>
</article>
<!-- Modal starts -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
        	<input class="btn btn-danger" type="submit" value="Delete">
        </form>
      </div>
    </div>
  </div>
</div>
 <!-- Modal Ends -->
{% endblock content %}

skillnecting/templates/profile-page.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="../static/assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="https://image.ibb.co/fZNTHz/skillnecting.png?{{ cache_id }}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    SKILLNECTING
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link href="../static/assets/css/material-kit.css?v=2.0.4" rel="stylesheet" />
  <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css">
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body class="profile-page sidebar-collapse">
  <nav class="navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg" color-on-scroll="100" id="sectionsNav">
    <div class="container">
      <div class="navbar-translate">
        {% if current_user.is_authenticated %}
        <a class="navbar-brand" href="/">{{current_user.username}}@Skillnecting</a>
        {% else %}
        <a class="navbar-brand" href="/">Skillnecting</a>
        {% endif %}
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="sr-only">Toggle navigation</span>
          <span class="navbar-toggler-icon"></span>
          <span class="navbar-toggler-icon"></span>
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
      <form class="form-inline">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
          <li class="dropdown nav-item">
            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
              <i class="material-icons">apps</i> Menu
            </a>
            <div class="dropdown-menu dropdown-with-icons">
              {% if current_user.is_authenticated %}
               <a href="{{ current_user.username }}" class="dropdown-item">
                  <i class="material-icons">perm_identity</i> My Profile
                </a>
                <a href="{{ url_for('users.account') }}" class="dropdown-item">
                  <i class="material-icons">edit</i> Edit Profile
                </a>
                <a href="{{ url_for('posts.new_post') }}" class="dropdown-item">
                  <i class="material-icons">message</i> New Post
                </a>
                <a href="{{ url_for('users.logout') }}" class="dropdown-item">
                  <i class="material-icons">stop</i> Log out
                </a>
              {% else %}
              <a href="{{ url_for('users.login') }}" class="dropdown-item">
                <i class="material-icons">play_arrow</i> Log in
              </a>
              <a href="{{ url_for('users.register') }}" class="dropdown-item">
                <i class="material-icons">how_to_reg</i> Register
              </a>
              {% endif %}
              <a href="{{ url_for('main.blog') }}" class="dropdown-item">
                <i class="material-icons">desktop_windows</i> Read Users Blogs
              </a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" rel="tooltip" title="" data-placement="bottom" href="#" target="_blank" data-original-title="Follow us on Twitter">
              <i class="fa fa-twitter"></i>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" rel="tooltip" title="" data-placement="bottom" href="#" target="_blank" data-original-title="Like us on Facebook">
              <i class="fa fa-facebook-square"></i>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" rel="tooltip" title="" data-placement="bottom" href="#" target="_blank" data-original-title="Follow us on Instagram">
              <i class="fa fa-instagram"></i>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="page-header header-filter" data-parallax="true" style="background-image: url('../static/assets/img/city-profile.jpg');"></div>
  <div class="main main-raised">
    <div class="profile-content">
      <div class="container">
        <div class="row">
          <div class="col-md-6 ml-auto mr-auto">
            <div class="profile">
              <div class="avatar">
                <img src="{{ url_for('static', filename='profile_pics/' + user.image_file) }}" alt="Circle Image" class="img-raised rounded-circle img-fluid">
              </div>
               <small class="col-md-2 ml-auto mr-auto text-success">
                {% with messages = get_flashed_messages(with_categories=true) %}
                  {% if messages %}
                    {% for category, message in messages %}
                      {{ message }}
                    {% endfor %}
                  {% endif %}
                {% endwith %}
              </small>
              <div class="name">
                <h3 class="title">{{ user.username }}</h3>
                <h6>{{ user.user_designation }}</h6>
                <div class="description text-center">
                  <p>{{ user.short_description }}</p>
                </div>
                {% for items in user.techskills %}
                  <i class="devicon-{{ items }}-plain colored" style="font-size:60px;"></i>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-6 ml-auto mr-auto">
          <div class="d-flex justify-content-center">
          <a href="https://www.github.com/{{ user.github_username }}" target="_blank">
            <img class="img-responsive" src="https://ghchart.rshah.org/{{ user.github_username }}" title="{{ user.username }}'s Github contribution chart">
          </a>
        </div>
          </div>
        <div class="row">
          <div class="col-md-6 ml-auto mr-auto">
            <div class="profile-tabs">
              <ul class="nav nav-pills nav-pills-icons justify-content-center" role="tablist">
                <li class="nav-item">
                  <a class="nav-link active" href="#website" role="tab" data-toggle="tab">
                    <i class="material-icons">web</i> Website
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#works" role="tab" data-toggle="tab">
                    <i class="material-icons">apps</i> Other Projects
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('users.user_posts', username=user.username) }}">
                    <i class="material-icons">question_answer</i> Read My Blog Posts
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="tab-content tab-space">
          <div class="tab-pane active text-center gallery" id="website">
            <div class="row">
              <div class="col-md-8 ml-auto mr-auto">
                  <div class="thumbnail-container">
                <div class="thumbnail">
                  <iframe name="Website" src="{{ user.user_weblink }}" width="550" height="550" frameborder="0" scrolling="yes" style="width: 100%;"></iframe>   
                </div>
            </div>
              </div>
            </div>
          </div>
          <div class="tab-pane text-center gallery" id="works">
            <div class="row">
              <div class="col-md-3 ml-auto">
                <img src="../static/assets/img/examples/mobile-app-onboarding-function.jpg" class="rounded">
                <img src="../static/assets/img/examples/app2-5908bba55dbc5-150x300.png" class="rounded">
                <img src="../static/assets/img/examples/cynthia-del-rio.jpg" class="rounded">
              </div>
              <div class="col-md-3 mr-auto">
                <img src="../static/assets/img/examples/mariya-georgieva.jpg" class="rounded">
                <img src="../static/assets/img/examples/clem-onojegaw.jpg" class="rounded">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <footer class="footer footer-default te">
    <div class="container">
      <div class="copyright text-center">
        &copy;
        <script>
          document.write(new Date().getFullYear())
        </script>, made with <i class="material-icons">favorite</i> by Flourishcodes using <a href="https://www.getbootstrap.com" target="_blank">Bootstraps</a> and inspiration from Creative Tim
      </div>
    </div>
  </footer>
  <!--   Core JS Files   -->
  <script src="../static/assets/js/core/jquery.min.js" type="text/javascript"></script>
  <script src="../static/assets/js/core/popper.min.js" type="text/javascript"></script>
  <script src="../static/assets/js/core/bootstrap-material-design.min.js" type="text/javascript"></script>
  <script src="../static/assets/js/plugins/moment.min.js"></script>
  <!--	Plugin for the Datepicker, full documentation here: https://github.com/Eonasdan/bootstrap-datetimepicker -->
  <script src="../static/assets/js/plugins/bootstrap-datetimepicker.js" type="text/javascript"></script>
  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
  <script src="../static/assets/js/plugins/nouislider.min.js" type="text/javascript"></script>
  <!--	Plugin for Sharrre btn -->
  <script src="../static/assets/js/plugins/jquery.sharrre.js" type="text/javascript"></script>
  <!-- Control Center for Material Kit: parallax effects, scripts for the example pages etc -->
  <script src="../static/assets/js/material-kit.js?v=2.0.4" type="text/javascript"></script>
  <script>
  $(document).ready(function(){
    
    
    var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-46172202-1']);
_gaq.push(['_trackPageview']);

(function() {
    var ga = document.createElement('script');
    ga.type = 'text/javascript';
    ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(ga, s);
})();

    // Facebook Pixel Code Don't Delete
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','//connect.facebook.net/en_US/fbevents.js');

try{
  fbq('init', '111649226022273');
  fbq('track', "PageView");

}catch(err) {
  console.log('Facebook Track Error:', err);
}

  });
</script>
<noscript>
  <img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=111649226022273&ev=PageView&noscript=1"
/>

</noscript>
</body>

</html>